booking/urls.py
from django.urls import path

from . import views


app_name='booking'


urlpatterns = [
    path('booking/<int:item_id>/', views.book_car, name='book_car'),
    path('rented-items/', views.rented_items, name='rented_items'),
    path('payment/', views.payment, name='payment'),
    path('success/', views.booking_success, name='success'),
]

conversation/urls.py
from django.urls import path

from . import views


app_name='conversation'


urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from . import views
from django.contrib.auth import views as auth_views
from . forms import LoginForm
from django.urls import path
from . import views


app_name='core'


urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('log/', views.log, name='log'),
    path('logout/', views.logout, name='logout'),
    path('about/', views.about, name='about'),
    path('car/', views.car, name='car'),
    path('feature/', views.feature, name='feature'),
    path('service/', views.service, name='service'),
    path('test/', views.test, name='test'),
    path('profile/', views.edit_profile, name='profile'),
    path('pass/', views.change_password, name='pass'),
    path('category/', views.category, name='category'),
    path('ask_login/', views.ask_login, name='ask_login'),

    

    

]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path
app_name='item'
from . import views
urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
   
]

rentacar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('booking/', include('booking.urls')),
  
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
import re
class LoginForm(AuthenticationForm):
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class':'w-full py-1 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Your password',
        'class':'w-full py-1 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'placeholder': 'Email'}),
        label="Email"
    )
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Username'}),
        label="Username"
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'}),
       
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}),
    )

    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']

    # Custom validation for password
    def clean_password1(self):
        password = self.cleaned_data.get('password1')
        if len(password) < 5:
            raise forms.ValidationError("Password must be at least 8 characters long.")
        
        # Check for at least one special character
        if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
            raise forms.ValidationError("Password must contain at least one special character.")

        # Check for at least one number
        if not re.search(r'\d', password):
            raise forms.ValidationError("Password must contain at least one number.")

        return password

    # Ensure the two passwords match
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match.")

        return password2

#To edit the profile
class EditProfileForm(forms.ModelForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'placeholder': 'Email'}),
        label="Email"
    )
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Username'}),
        label="Username"
    )

    class Meta:
        model = User
        fields = ['email', 'username']

#To edit the password
class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Old Password",
        widget=forms.PasswordInput(attrs={'placeholder': 'Old Password'})
    )
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(attrs={'placeholder': 'New Password'})
    )
    new_password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirm New Password'})
    )

core/views.py
from django.shortcuts import render,redirect
from .forms import SignupForm
from django.contrib.auth import authenticate, login as auth_login
from django.contrib import messages
from item.models import Category, Item
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from .forms import EditProfileForm, CustomPasswordChangeForm
from django.contrib.auth import logout as auth_logout

# Create your views here.
def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories' : categories,
        'items' : items
    })
def category(request):
    
    return render(request, 'core/category.html')

def contact(request):
    return render(request, 'core/contact.html')


def ask_login(request):
    action = request.GET.get('action', '')  # Get the action parameter from the URL
    message = "Welcome! You need to log in to contact the seller." if action == "contact" else "Welcome! You need to log in to book the car."

    return render(request, 'core/ask_login.html', {'message': message})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {
        'form' : form
    })

@login_required  # Ensure the user is logged in
def log(request):
    items = Item.objects.all()# Get a few items for display
    categories = Category.objects.all()
    filter_item = Item.objects.exclude(created_by=request.user)
    

    # Calculate the count of items per category that are not created by the logged-in user
    for category in categories:
        category.item_count = category.items.exclude(created_by=request.user).count()


    return render(request, 'core/index2.html', {
        'categories': categories,
        'items': items,
        'filter_item': filter_item
    })

def logout(request):
    auth_logout(request)
    return redirect('core:index') 

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('log')  # Redirect to index2.html or your logged-in page
        else:
            messages.error(request, 'Invalid username or password.')
    
    return render(request, 'core/login.html')  # Show the login form if not POST
def about(request):
    return render(request, 'core/about.html')

def car(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/cars.html', {
        'categories' : categories,
        'items' : items
    })


def feature(request):
    return render(request, 'core/feature.html')

def service(request):
    return render(request, 'core/service.html')

def test(request):
    return render(request, 'core/testimonial.html')

#To edit profile

@login_required
def edit_profile(request):
    profile_form = None
    if request.method == 'POST':
        # Handle profile update
        profile_form = EditProfileForm(request.POST, instance=request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile has been updated successfully!')
            return redirect('core:log')  # Redirect to the appropriate page after successful update

    else:
        profile_form = EditProfileForm(instance=request.user)

    return render(request, 'core/profile.html', {
        'profile_form': profile_form
    })


@login_required
def change_password(request):
    password_form = None
    if request.method == 'POST':
        # Handle password change
        password_form = CustomPasswordChangeForm(user=request.user, data=request.POST)
        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)  # Prevent logout after password change
            messages.success(request, 'Your password was successfully updated!')
            return redirect('core:log')  # Redirect to the appropriate page after successful password change

    else:
        password_form = CustomPasswordChangeForm(user=request.user)

    return render(request, 'core/password.html', {
        'password_form': password_form
    })

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>Rent a car</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>

        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
      <!-- Topbar Start -->
      <div class="container-fluid topbar bg-secondary d-none d-xl-block w-100">
        <div class="container">
            <div class="row gx-0 align-items-center" style="height: 45px;">
                <div class="col-lg-6 text-center text-lg-start mb-lg-0">
                    <div class="d-flex flex-wrap">
                        <a href="#" class="text-muted me-4"><i class="fas fa-map-marker-alt text-primary me-2"></i>Find A Location</a>
                        <a href="tel:+01234567890" class="text-muted me-4"><i class="fas fa-phone-alt text-primary me-2"></i>+01234567890</a>
                        <a href="mailto:example@gmail.com" class="text-muted me-0"><i class="fas fa-envelope text-primary me-2"></i>Example@gmail.com</a>
                    </div>
                </div>
                <div class="col-lg-6 text-center text-lg-end">
                    <div class="d-flex align-items-center justify-content-end">
                        <a href="#" class="btn btn-light btn-sm-square rounded-circle me-3"><i class="fab fa-facebook-f"></i></a>
                        <a href="#" class="btn btn-light btn-sm-square rounded-circle me-3"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="btn btn-light btn-sm-square rounded-circle me-3"><i class="fab fa-instagram"></i></a>
                        <a href="#" class="btn btn-light btn-sm-square rounded-circle me-0"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <div class="container-fluid nav-bar sticky-top px-0 px-lg-4 py-2 py-lg-0">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light ">
                <a href="" class="navbar-brand p-0">
                    <h1 class="display-6 text-primary">
                        <img src="{% static 'img/transport.png' %}" alt="Car Icon" style="width: 40px; height: auto; margin-right: 10px;">
                        Cental
                    </h1>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav mx-auto py-0">
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'core:log' %}" class="nav-item nav-link {% block home2 %}{% endblock home2 %}">Home</a>
      
                            <a href="{% url 'dashboard:index' %}" class="nav-item nav-link {% block dashboard %}{% endblock dashboard %}">Dashboard</a>
                            <a href="{% url 'conversation:inbox' %}" class="nav-item nav-link {% block inbox %}{% endblock inbox %}">Inbox</a>
                            <a href="{% url 'item:new' %}" class="nav-item nav-link {% block item %}{% endblock item %}">Add Item</a>
                            <a href="{% url 'booking:rented_items' %}" class="nav-item nav-link {% block book %}{% endblock book %}">Book</a>
                            <a href="{% url 'item:items' %}" class="nav-item nav-link {% block  browse %}{% endblock browse %}">Browse</a>
                        </div>
                                                                
                        <div class="nav-item  me-1">
                      
                        <a href="{% url 'core:logout' %}" class="btn btn-primary rounded-pill py-2 px-4">Logout</a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'core:profile' %}" class="btn btn-primary rounded-pill py-2 px-4">Edit profile</a>
                    </div>
                        {% else %}
                            <a href="{% url 'core:index' %}" class="nav-item nav-link {% block home %}{% endblock home %}">Home</a>
                            <a href="{% url 'core:about' %}" class="nav-item nav-link {% block about %}{% endblock about %}">About</a>
                            <a href="{% url 'core:service' %}" class="nav-item nav-link {% block service %}{% endblock service %}">Service</a>
                            <div class="nav-item dropdown ">
                                <a href="#" class="nav-link dropdown-toggle {% block page %}{% endblock page %}" data-bs-toggle="dropdown">Pages</a>
                                <div class="dropdown-menu m-0">
                                    <a href="{% url 'core:feature' %}" class="dropdown-item {% block feature %}{% endblock feature %}">Our Feature</a>
                                    <a href="{% url 'core:car' %}" class="dropdown-item {% block car %}{% endblock car %}">Our Cars</a>
                                    <a href="{% url 'core:test' %}" class="dropdown-item {% block test %}{% endblock test %}">Testimonial</a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'core:signup' %}" class="btn btn-primary rounded-pill py-2 px-4">Sign Up</a>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'core:login' %}" class="btn btn-primary rounded-pill py-2 px-4">Log In</a>
                    </div>
                        {% endif %}
                    
            </nav>
        </div>
    </div>


        <body style="background-color:LightGray;">
            
            {% block content %}{% endblock content %}
        </body>

   <!-- Footer Start -->
   <div class="container-fluid footer py-5 wow fadeIn" data-wow-delay="0.2s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-md-6 col-lg-6 col-xl-3">
                <div class="footer-item d-flex flex-column">
                    <div class="footer-item">
                        <h4 class="text-white mb-4">About Us</h4>
                        <p class="mb-3">Dolor amet sit justo amet elitr clita ipsum elitr est.Lorem ipsum dolor sit amet, consectetur adipiscing elit consectetur adipiscing elit.</p>
                    </div>
                    <div class="position-relative">
                        <input class="form-control rounded-pill w-100 py-3 ps-4 pe-5" type="text" placeholder="Enter your email">
                        <button type="button" class="btn btn-secondary rounded-pill position-absolute top-0 end-0 py-2 mt-2 me-2">Subscribe</button>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-3">
                <div class="footer-item d-flex flex-column">
                    <h4 class="text-white mb-4">Quick Links</h4>
                    <a href="#"><i class="fas fa-angle-right me-2"></i> About</a>
                    <a href="#"><i class="fas fa-angle-right me-2"></i> Cars</a>
                    <a href="#"><i class="fas fa-angle-right me-2"></i> Car Types</a>
                    <a href="#"><i class="fas fa-angle-right me-2"></i> Team</a>
                    <a href="{% url 'core:contact' %}"><i class="fas fa-angle-right me-2"></i> Contact us</a>
                    <a href="#"><i class="fas fa-angle-right me-2"></i> Terms & Conditions</a>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-3">
                <div class="footer-item d-flex flex-column">
                    <h4 class="text-white mb-4">Business Hours</h4>
                    <div class="mb-3">
                        <h6 class="text-muted mb-0">Mon - Friday:</h6>
                        <p class="text-white mb-0">09.00 am to 07.00 pm</p>
                    </div>
                    <div class="mb-3">
                        <h6 class="text-muted mb-0">Saturday:</h6>
                        <p class="text-white mb-0">10.00 am to 05.00 pm</p>
                    </div>
                    <div class="mb-3">
                        <h6 class="text-muted mb-0">Vacation:</h6>
                        <p class="text-white mb-0">All Sunday is our vacation</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-3">
                <div class="footer-item d-flex flex-column">
                    <h4 class="text-white mb-4">Contact Info</h4>
                    <a href="#"><i class="fa fa-map-marker-alt me-2"></i> 123 Street, New York, USA</a>
                    <a href="mailto:info@example.com"><i class="fas fa-envelope me-2"></i> info@example.com</a>
                    <a href="tel:+012 345 67890"><i class="fas fa-phone me-2"></i> +012 345 67890</a>
                    <a href="tel:+012 345 67890" class="mb-3"><i class="fas fa-print me-2"></i> +012 345 67890</a>
                    <div class="d-flex">
                        <a class="btn btn-secondary btn-md-square rounded-circle me-3" href=""><i class="fab fa-facebook-f text-white"></i></a>
                        <a class="btn btn-secondary btn-md-square rounded-circle me-3" href=""><i class="fab fa-twitter text-white"></i></a>
                        <a class="btn btn-secondary btn-md-square rounded-circle me-3" href=""><i class="fab fa-instagram text-white"></i></a>
                        <a class="btn btn-secondary btn-md-square rounded-circle me-0" href=""><i class="fab fa-linkedin-in text-white"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

<!-- Copyright Start -->
<div class="container-fluid copyright py-4">
    <div class="container">
        <div class="row g-4 align-items-center">
            <div class="col-md-6 text-center text-md-start mb-md-0">
                <span class="text-body"><a href="#" class="border-bottom text-white"><i class="fas fa-copyright text-light me-2"></i>Your Site Name</a>, All right reserved.</span>
            </div>
            <div class="col-md-6 text-center text-md-end text-body">
                <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->
                <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->
                <!--/*** you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". ***/-->
                Designed By <a class="border-bottom text-white" href="https://htmlcodex.com">HTML Codex</a>
            </div>
        </div>
    </div>
</div>
<!-- Copyright End -->


<!-- Back to Top -->
<a href="#" class="btn btn-secondary btn-lg-square rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>   


<!-- JavaScript Libraries -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>


<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>      

core/templates/core/category.html
{% extends "core/base.html" %}

core/templates/core/profile.html
{% extends "core/base.html" %}
{% load static %}

{% block login %}
<a href="blog.html" class="nav-item nav-link">Booking</a>
<a href="blog.html" class="nav-item nav-link">Edit</a>
{% endblock login %}

{% block signin %}


<div>
        <a href="{% url 'core:logout' %}" class="btn btn-primary rounded-pill py-2 px-4">logout</a>
        </div>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <div>
                <a href="{% url 'core:signup' %}" class="btn btn-primary rounded-pill py-2 px-4">Inbox</a>
                        </div>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                        <div>
                        <a href="{% url 'core:login' %}" class="btn btn-primary rounded-pill py-2 px-4">Dashboard</a>
                        </div>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        
                        <div>
                            <a href="{% url 'core:profile' %}" class="btn btn-primary rounded-pill py-2 px-4">Edit profile</a>

                            </div>
    
{% endblock signin %}
{% block content %}
<!-- Carousel Start -->
<div class="header-carousel">
    <div id="carouselId" class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">
        <ol class="carousel-indicators">
            <li data-bs-target="#carouselId" data-bs-slide-to="0" class="active" aria-current="true" aria-label="First slide"></li>
            <li data-bs-target="#carouselId" data-bs-slide-to="1" aria-label="Second slide"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img src="{% static 'img/carousel-2.jpg' %}" class="img-fluid w-100" alt="First slide"/>
                <div class="carousel-caption">
                    <div class="container py-4">
                        <div class="row g-5">
                            <div class="col-lg-6 fadeInLeft animated" data-animation="fadeInLeft" data-delay="1s" style="animation-delay: 1s;">
                                        <div class="bg-secondary rounded p-5">
                                            {% comment %} <h1 style="color:white;"></h1> {% endcomment %}
                                            <h1 class="display-6 " style="color:white;">
                                                <img src="{% static 'img/car-icon.png' %}" alt="Car Icon" style="width: 50px; height: auto; margin-right: 10px;">
                                                Edit Profile
                                            </h1>
                                            
                                          
                                            <center>
                                                
                                                <form method="POST" action="" id="profileForm" class="mb-4">
                                                    {% csrf_token %}
                                                    <table>
                                               
                                                <div class="form-group">
                                                    <tr style="margin-bottom: 20px;">  <!-- Add spacing between fields -->
                                                        <th>
                                                            {{ profile_form.username.label_tag }}
                                                        </th>
                                                        <th>
                                                            
                                                            {{ profile_form.username }}
                                                        </th>
                                                    </tr>
                                                    
                                                </div>
                                                
                                                <div class="form-group">
                                                    <tr style="height: 20px;"></tr> <!-- Empty row for spacing -->
                                                    
                                                    <th>
                                                        {{ profile_form.email.label_tag }}
                                                    </th>
                                                    <th>
                                                        
                                                        {{ profile_form.email }}
                                                    </th>
                                                </tr>
                                                </div>
                                                <br>
                                            </table>
                                            <br>
                                            <button type="submit" name="profile_submit" class="btn btn-outline-light btn-lg">Update Profile</button>
                                            <br>
                                            <br>
                                            <div class="signup-link">change password ? <a href="{% url 'core:pass' %}">update password</a></div>
                                        </form>
                                        
                                                                                    </center>
                                        
                                        
                                        {% comment %}                                             
                                        <form method="POST" action="" id="passwordForm">
                                            {% csrf_token %}
                                            <h3>Change Password</h3>
                                            <div class="form-group">
                                                {{ password_form.old_password.label_tag }}
                                                    {{ password_form.old_password }}
                                                </div>
                                                <div class="form-group">
                                                    {{ password_form.new_password1.label_tag }}
                                                    {{ password_form.new_password1 }}
                                                </div>
                                                <div class="form-group">
                                                    {{ password_form.new_password2.label_tag }}
                                                    {{ password_form.new_password2 }}
                                                </div>
                                                <button type="submit" name="password_submit" class="btn btn-primary">Change Password</button>
                                            </form> {% endcomment %}
  
                                            
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    
    </html>
    {% endblock content %}