booking/urls.py
from django.urls import path

from . import views


app_name='booking'


urlpatterns = [
    path('booking/<int:item_id>/', views.book_car, name='book_car'),
    path('rented-items/', views.rented_items, name='rented_items'),
    path('payment/', views.payment, name='payment'),
    path('success/', views.booking_success, name='success'),
]

conversation/urls.py
from django.urls import path

from . import views


app_name='conversation'


urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from . import views
from django.contrib.auth import views as auth_views
from . forms import LoginForm
from django.urls import path
from . import views


app_name='core'


urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('log/', views.log, name='log'),
    path('logout/', views.logout, name='logout'),
    path('about/', views.about, name='about'),
    path('car/', views.car, name='car'),
    path('feature/', views.feature, name='feature'),
    path('service/', views.service, name='service'),
    path('test/', views.test, name='test'),
    path('profile/', views.edit_profile, name='profile'),
    path('pass/', views.change_password, name='pass'),
    path('category/', views.category, name='category'),
    path('ask_login/', views.ask_login, name='ask_login'),

    

    

]

item/urls.py
from django.urls import path
app_name='item'
from . import views
urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
   
]

rentacar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('booking/', include('booking.urls')),
  
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def get_category_image(self):
        # Get the first item in the category that has an image
        first_item_with_image = self.items.filter(image__isnull=False).first()
        # Return the image URL if an item with an image is found, else return None
        return first_item_with_image.image.url if first_item_with_image else None
    def __str__(self) -> str:
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    company = models.CharField(max_length=255, blank=True, null=True)
    model = models.CharField(max_length=255, blank=True, null=True)
    seats = models.IntegerField(blank=True, null=True)
    fuel_type = models.CharField(max_length=255, blank=True, null=True)
    gear_type = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

item/forms.py
from django import forms
from .models import Item, Category
from django import forms
from .models import Item, Category

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={
            'class': INPUT_CLASSES,
            'style': 'width: 100%; height: 40px;',
        }),
        required=False,
        empty_label="Select Existing Category",
    )

    new_category = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'placeholder': 'Or Add New Category',
            'class': INPUT_CLASSES,
            'style': 'width: 100%; height: 20px;',
        })
    )

    class Meta:
        model = Item
        fields = ('category', 'new_category', 'name', 'description', 'price', 'image', 'company', 'model', 'seats', 'fuel_type', 'gear_type')
        
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Enter Item Name',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'company': forms.TextInput(attrs={
                'placeholder': 'Enter Item Company',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'model': forms.TextInput(attrs={
                'placeholder': 'Enter Item Model',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'seats': forms.TextInput(attrs={
                'placeholder': 'Enter Number of Seats',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'fuel_type': forms.TextInput(attrs={
                'placeholder': 'Enter Item Fuel Type',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'gear_type': forms.TextInput(attrs={
                'placeholder': 'Enter Item Gear Type',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'Enter Item Description',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 100px;',
            }),
            'price': forms.TextInput(attrs={
                'placeholder': 'Enter Item Price',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
        }

    def clean(self):
        cleaned_data = super().clean()
        category = cleaned_data.get('category')
        new_category = cleaned_data.get('new_category')
        name = cleaned_data.get('name')
        image = cleaned_data.get('image')

        # Ensure either an existing category is selected or a new category is provided
        if not category and not new_category:
            raise forms.ValidationError('Please select an existing category or add a new category.')

        # Ensure name is provided
        if not name:
            raise forms.ValidationError('Item name is required.')

        # Ensure an image is uploaded
        if not image:
            raise forms.ValidationError('An image is required.')

        return cleaned_data



class EditItemForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={
            'class': INPUT_CLASSES,
            'style': 'width: 100%; height: 40px;',
        })
    )

    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image', 'company', 'model', 'seats', 'fuel_type', 'gear_type', 'is_sold')

        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Enter Item Name',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'company': forms.TextInput(attrs={
                'placeholder': 'Enter Item Company',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'model': forms.TextInput(attrs={
                'placeholder': 'Enter Item Model',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'seats': forms.TextInput(attrs={
                'placeholder': 'Enter Number of Seats',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'fuel_type': forms.TextInput(attrs={
                'placeholder': 'Enter Item Fuel Type',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'gear_type': forms.TextInput(attrs={
                'placeholder': 'Enter Item Gear Type',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'description': forms.Textarea(attrs={
                'placeholder': 'Enter Item Description',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 100px;',
            }),
            'price': forms.TextInput(attrs={
                'placeholder': 'Enter Item Price',
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
                'style': 'width: 100%; height: 20px;',
            }),
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . models import Item, Category
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm,EditItemForm
from django.db.models import Q



@login_required
def items(request):
    query = request.GET.get('query', '')  # Search query
    category_id = request.GET.get('category', 0)  # Category filter
    seats = request.GET.get('seats', '')  # Seat filter (as a string)
    items = Item.objects.exclude(created_by=request.user)  # Only get available items
    categories = Category.objects.all()  # All categories

    if category_id :
        items = items.filter(category_id=category_id)
    # Filter by query (searching by name, company, model, or category)
    if query:
        items = items.filter(
            Q(name__icontains=query) |
            Q(company__icontains=query) |
            Q(model__icontains=query) 
            
        )

    # Filter by seat number if provided and it's a valid digit
    if seats.isdigit():
        items = items.filter(seats=int(seats))  # Correct field is `seats`
    # Render the template with the filtered items and form values
    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
        'seats': seats,  # Pass the seats back to the template
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)

    # Filter related items based on category and availability
    related_items = Item.objects.filter(
        category=item.category,
        is_sold=False
    ).exclude(pk=pk)

    # Only exclude items created by the user if the user is authenticated
    if request.user.is_authenticated:
        related_items = related_items.exclude(created_by=request.user)

    related_items = related_items[:10]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            # Proceed with saving the item as before
            new_category_name = form.cleaned_data.get('new_category')
            if new_category_name:
                category, created = Category.objects.get_or_create(name=new_category_name)
            else:
                category = form.cleaned_data.get('category')

            item = form.save(commit=False)
            item.created_by = request.user
            item.category = category
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'title': 'Add New Item',
        'form': form
    })



@login_required
def delete(request,pk):
    item=get_object_or_404(Item,pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')



@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'title': 'Edit Item',
        'form': form,
        'item': item  # Pass the item to the template
    })

item/templates/item/detail.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<br><br>




<div class="container my-5"> 
    <div class="row">
        <!-- Carousel Image on the left -->
        <div class="col-sm-7">
            <div class="card p-2" style="width: auto; height: 90%;">
                <div id="Vehicle_{{vehicle.Vehicle_license_plate}}" class="carousel slide" data-interval="false">
                    <ol class="carousel-indicators">
                        <li data-target="#Vehicle_{{vehicle.Vehicle_license_plate}}" data-slide-to="0" class="active"></li>
                        <li data-target="#Vehicle_{{vehicle.Vehicle_license_plate}}" data-slide-to="1"></li>
                        <li data-target="#Vehicle_{{vehicle.Vehicle_license_plate}}" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="{{ item.image.url }}" alt="First slide" style="height: 400px; object-fit: cover;">
                        </div>
                        
                    </div>
                   
                </div>
            </div>
        </div>

        <!-- Information on the right -->
        <div class="col-sm-5">
            <div class="card p-2" style="width: auto;">
                <div class="card-body">
                    <div class="row ">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ item.name }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Company</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ item.company }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Model</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ item.model }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Fuel Type</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ item.fuel_type }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Seats</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ item.seats }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Gear Type</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {% if item.isGeared %} Manual {% else %} Auto {% endif %}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">About</h6>
                        </div>
                        {% if item.description %}
                        <div class="col-sm-9 text-secondary">
                            {{ item.description }}
                        </div>
                        {% endif %}
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Price</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            ₹{{ item.price }} (per day)
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Seller</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {{ item.created_by }}
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Is Sold</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                            {% if item.is_sold %}
                                <!-- Display a green tick mark if item is sold -->
                                <span style="color: green;">&#x2705;</span> <!-- Unicode for a green tick -->
                            {% else %}
                                <!-- Display a cross mark in a box if item is not sold -->
                                <span style="color: red;">&#x274C;</span> <!-- Unicode for a cross mark in a box -->
                            {% endif %}
                        </div>
                    </div>
                    <hr>
                    
<center>
    <br>
{% if request.user == item.created_by %}

<div class="d-flex justify-content-center mt-4">

    <a href="{% url 'item:edit' item.id %}" class="btn btn-success me-4">Edit</a>
    <a href="{% url 'item:delete' item.id %}" class="btn btn-primary">Delete</a>
   

    
</div>
{% else %}
{% if not user.is_authenticated %}
<div class="d-flex justify-content-center mt-4">
    <a href="{% url 'core:ask_login' %}?action=contact" class="btn btn-primary me-4">Contact Seller</a>
    <a href="{% url 'core:ask_login' %}?action=book" class="btn btn-success">Book</a>
</div>
{% else %}
<div class="d-flex justify-content-center mt-4">
    <a href="{% url 'conversation:new' item.id %}" class="btn btn-primary me-4">Contact Seller</a>
    <a href="{% url 'booking:book_car' item.id %}" class="btn btn-success">Book</a>
</div>
{% endif %}

    {% endif %}
</center>
                </div>
            </div>
        </div>
    </div>
</div> 

<!-- Related Car Start -->
<div class="container-fluid categories pb-5">
    <div class="container pb-5">
        <div class="text-center mx-auto pb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 800px;">
            <h1 class="display-5 text-capitalize mb-3">Related<span class="text-primary">Cars</span></h1>
            <p class="mb-0"></p></div>

        <!-- Add arrow controls before the carousel -->
        <div class="d-flex justify-content-between align-items-center mb-3">
            <button class="owl-prev btn btn-primary"><i class="fas fa-arrow-left"></i></button>
            <button class="owl-next btn btn-primary"><i class="fas fa-arrow-right"></i></button>
        </div>

        <div class="categories-carousel owl-carousel wow fadeInUp" data-wow-delay="0.1s">
            {% if related_items %}
                {% for item in related_items %}
            <div class="categories-item p-4">
                <div class="categories-item-inner">
                    <a href="{% url 'item:detail' item.id %}">
                    <div class="categories-img rounded-top" style="height: 200px; overflow: hidden;">
                        <img src="{{ item.image.url }}" class="img-fluid w-100" style="height: 100%; object-fit: cover;" alt="">
                    </div>
                    <div class="categories-content rounded-bottom p-4">
                        <h4>{{ item.name }}</h4>
                        <div class="categories-review mb-4">
                            <div class="me-3">4.5 Review</div>
                            <div class="d-flex justify-content-center text-secondary">
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star"></i>
                                <i class="fas fa-star text-body"></i>
                            </div>
                        </div>
                        <div class="mb-4">
                            <h4 class="bg-white text-primary rounded-pill py-2 px-4 mb-0">Price: {{ item.price }} / Day</h4>
                        </div>
                        <a href="{% url 'item:detail' item.id %}" class="btn btn-primary" >Show Details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
                <div class="categories-item p-4">
                    <p>No related cars available.</p>
                </div>
            {% endif %}
        </div>
    </div>
</div>
<!-- Car End -->
{% endblock content %}

item/templates/item/items.html
{% extends "core/base.html" %}
{% block browse %}active{% endblock browse %}
{% load static %}

{% block content %}
<!-- Header Start -->
<div class="container-fluid bg-breadcrumb">
    <div class="container text-center py-5" style="max-width: 900px;">
        <h4 class="text-white display-4 mb-4 wow fadeInDown" data-wow-delay="0.1s">Search</h4>
        <ol class="breadcrumb d-flex justify-content-center mb-0 wow fadeInDown" data-wow-delay="0.3s">
            <li class="breadcrumb-item"><a href="{% url 'core:log' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Pages</a></li>
            <li class="breadcrumb-item active text-primary">Search</li>
        </ol>    
    </div>
</div>
<!-- Header End -->
<br><br>


<div class="container-fluid">
    <div class="row">
      <!-- Sidebar Start -->
<br>
<div class="col-md-3 bg-secondary text-white" style="padding: 10px;">
    <br>
    <h3 class="display-6 text-center" style="color: white;">
        Search 
        <img src="{% static 'img/vintage-car.png' %}" alt="Car Icon" style="width: 100px; height: auto; margin-right: 10px;">
    </h3>
    <br>
    <form method="get" action="{% url 'item:items' %}">
        {% csrf_token %}
        <!-- Search input -->
        <input name="query" class="w-100 py-2 px-2 border rounded" type="text" value="{{ query }}" placeholder="Search for Name, model, company...">
        <div style="margin-top: 20px;" class="d-flex justify-content-end">
            <button class="btn btn-outline-light btn-md">Search</button>
        </div>
    </form>
    <hr class="my-2">
    <br>
    
    <!-- Categories Section -->
    <h4 class="text-center" style="color: white;">Categories</h4>
    <ul class="list-unstyled">
        {% for category in categories %}
            <li class="py-2{% if category.id == category_id %} bg-gray-200{% endif %}">
                <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}" class="text-white">
                    {{ category.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <hr class="my-2">
    <br>
    
    <!-- Seats Filter Section -->
    <h4 class="text-center" style="color: white;">Seats</h4>
    <div class="seat-filter">
        <form method="get" action="{% url 'item:items' %}">
            <label for="seats" style="color: white;">Filter by Seats:</label>
            <input type="number" id="seats" name="seats" value="{{ seats }}" placeholder="Enter number of seats" class="form-control">
            <br>
            <button type="submit" class="btn btn-outline-light mt-2">Apply Filter</button>
        </form>
    </div>
    <br>
    <hr class="my-2">
    
    <!-- Clear Filters Section -->
    <center>
        <p class="font-semibold">Clear Filters</p>
        <a href="{% url 'item:items' %}" class="btn btn-outline-light btn-md">Clear</a>
    </center>
</div>
<!-- Sidebar End -->

        <!-- Main Content Start -->
        <div class="col-md-9">
            <div class="container-fluid categories pb-5">
                <div class="container pb-5">
                    <div class="text-center mx-auto pb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 800px;">
                        <h1 class="display-5 text-capitalize mb-3">All<span class="text-primary">Cars</span></h1>
                        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut amet nemo expedita asperiores commodi accusantium at cum harum, excepturi, quia tempora cupiditate! Adipisci facilis modi quisquam quia distinctio.</p>
                    </div>
                    <br>
                    <div class="row wow fadeInUp" data-wow-delay="0.1s">
                        {% if items.count == 1 %}
                        <div class="col-md-4">
                            <div class="categories-item p-4">
                                <div class="categories-item-inner">
                                    <a href="{% url 'item:detail' items.first.id %}">
                                        <div class="categories-img rounded-top" style="height: 200px; overflow: hidden;">
                                            <img src="{{ items.first.image.url }}" class="img-fluid w-100" style="height: 100%; object-fit: cover;" alt="">
                                        </div>
                                        <div class="categories-content rounded-bottom p-4">
                                            <h4>{{ items.first.name }}</h4>
                                            <div class="categories-review mb-4">
                                                <div class="me-3">4.5 Review</div>
                                                <div class="d-flex justify-content-center text-secondary">
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star"></i>
                                                    <i class="fas fa-star text-body"></i>
                                                </div>
                                            </div>
                                            <div class="mb-4">
                                                <h4 class="bg-white text-primary rounded-pill py-2 px-4 mb-0">Price: {{ items.first.price }} / Day</h4>
                                            </div>
                                            <a href="{% url 'item:detail' items.first.id %}" class="btn btn-primary" target="_blank">Show Details</a>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="row">
                            {% for item in items %}
                            <div class="col-md-4 mb-4">
                                <div class="categories-item p-4">
                                    <div class="categories-item-inner">
                                        <a href="{% url 'item:detail' item.id %}">
                                            <div class="categories-img rounded-top" style="height: 200px; overflow: hidden;">
                                                <img src="{{ item.image.url }}" class="img-fluid w-100" style="height: 100%; object-fit: cover;" alt="">
                                            </div>
                                            <div class="categories-content rounded-bottom p-4">
                                                <h4>{{ item.name }}</h4>
                                                <div class="categories-review mb-4">
                                                    <div class="me-3">4.5 Review</div>
                                                    <div class="d-flex justify-content-center text-secondary">
                                                        <i class="fas fa-star"></i>
                                                        <i class="fas fa-star"></i>
                                                        <i class="fas fa-star"></i>
                                                        <i class="fas fa-star"></i>
                                                        <i class="fas fa-star text-body"></i>
                                                    </div>
                                                </div>
                                                <div class="mb-4">
                                                    <h4 class="bg-white text-primary rounded-pill py-2 px-4 mb-0">Price: {{ item.price }} / Day</h4>
                                                </div>
                                                <a href="{% url 'item:detail' item.id %}" class="btn btn-primary" >Show Details</a>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Content End -->
    </div>
</div>

{% endblock content %}