core/urls.py
from . import views
from django.contrib.auth import views as auth_views
from . forms import LoginForm
from django.urls import path
from . import views


app_name='core'


urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('log/', views.log, name='log'),
    path('logout/', views.logout, name='logout'),
    path('about/', views.about, name='about'),
    path('car/', views.car, name='car'),
    path('feature/', views.feature, name='feature'),
    path('service/', views.service, name='service'),
    path('test/', views.test, name='test'),
    path('profile/', views.edit_profile, name='profile'),
    path('pass/', views.change_password, name='pass'),
    path('category/', views.category, name='category'),
    path('ask_login/', views.ask_login, name='ask_login'),

    

    

]

dashboard/urls.py
from django.urls import path

from dashboard import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path
app_name='item'
from . import views
urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
   
]

rentacar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('booking/', include('booking.urls')),
  
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from item.models import Item
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)

    return render(request, 'dashboard/index.html', {
        'items': items,
    })

dashboard/templates/dashboard/index.html
{% extends "core/base.html" %}
{% block dashboard %}active{% endblock dashboard %}

{% block content %} 

  
    <br>
    <br>
<!-- Car Start -->
<div class="container-fluid categories pb-5">
    <div class="container pb-5">
      <div class="text-center mx-auto pb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 800px;">
        <h1 class="display-5 text-capitalize mb-3">My<span class="text-primary">Cars</span></h1>
        <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut amet nemo expedita asperiores commodi accusantium at cum harum, excepturi, quia tempora cupiditate! Adipisci facilis modi quisquam quia distinctio.</p>
      </div>
  <br>
      <div class="row wow fadeInUp" data-wow-delay="0.1s">
        {% if items.count == 1 %}
        <div class="col-md-4">
          <div class="categories-item p-4">
            <div class="categories-item-inner">
              <a href="{% url 'item:detail' items.first.id %}">
                <div class="categories-img rounded-top" style="height: 200px; overflow: hidden;">
                  <img src="{{ items.first.image.url }}" class="img-fluid w-100" style="height: 100%; object-fit: cover;" alt="">
                </div>
                <div class="categories-content rounded-bottom p-4">
                  <h4>{{ items.first.name }}</h4>
                  <div class="categories-review mb-4">
                    <div class="me-3">4.5 Review</div>
                    <div class="d-flex justify-content-center text-secondary">
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star text-body"></i>
                    </div>
                  </div>
                  <div class="mb-4">
                    <h4 class="bg-white text-primary rounded-pill py-2 px-4 mb-0">Price: {{ items.first.price }} / Day</h4>
                  </div>
                  <a href="{% url 'item:detail' items.first.id %}" class="btn btn-primary" target="_blank">Show Details</a>
                </div>
              </a>
            </div>
          </div>
        </div>
        {% else %}
        <div class="row">
        {% for item in items %}
        <div class="col-md-4 mb-4">
            <div class="categories-item p-4">
              <div class="categories-item-inner">
                <a href="{% url 'item:detail' items.first.id %}">
                  <div class="categories-img rounded-top" style="height: 200px; overflow: hidden;">
                    <img src="{{ item.image.url }}" class="img-fluid w-100" style="height: 100%; object-fit: cover;" alt="">
                  </div>
                  <div class="categories-content rounded-bottom p-4">
                    <h4>{{ item.name }}</h4>
                    <div class="categories-review mb-4">
                      <div class="me-3">4.5 Review</div>
                      <div class="d-flex justify-content-center text-secondary">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star text-body"></i>
                      </div>
                    </div>
                    <div class="mb-4">
                      <h4 class="bg-white text-primary rounded-pill py-2 px-4 mb-0">Price: {{ item.price }} / Day</h4>
                    </div>
                    <a href="{% url 'item:detail' item.id %}" class="btn btn-primary">Show Details</a>
                  </div>
                </a>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
</div>

{% endblock content %}